package com.bilibili.cluster.scheduler.api.enums;

public enum RedisLockKey {

    GLOBAL_UPDATE_SCHEDULER_EXECUTE_NODE_STATUS_LOCK_KEY,

    GLOBAL_UPDATE_SCHEDULER_EXECUTE_FLOW_STATUS_LOCK_KEY,

    BMR_DEPLOY_DOLPHIN_SCHEDULER_PRE_ALIGN_LOCK_KEY,

    BMR_DEPLOY_DOLPHIN_SCHEDULER_UPDATE_TASK_DETAIL_KEY,

    BMR_DEPLOY_BATCH_TASK_EVENT_PRE_ALIGN_LOCK_KEY,

    BMR_DEPLOY_SCHEDULER_APPLY_ONE_FLOW_LOCK_KEY,

    BMR_DEPLOY_SCHEDULER_EXECUTE_ONE_FLOW_LOCK_KEY,

    BMR_DEPLOY_SCHEDULER_PREPARE_ONE_FLOW_LOCK_KEY,

    ;

}
