server:
  port: 8080
  servlet:
    session:
      timeout: 120m
    context-path: /bmr/cluster/scheduler/
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  jetty:
    max-http-form-post-size: 5000000

spring:
  main:
    allow-circular-references: true
  banner:
    charset: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
  messages:
    basename: i18n/messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/saber_jobs_info?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&serverTimezone=GMT%2B8
    #    username: saber
    #    password: saber123
    jdbc-url: jdbc:mysql://127.0.0.1:3306/bmr-scheduler?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: cyclonejoker
    hikari:
      connection-test-query: select 1
      minimum-idle: 5
      auto-commit: true
      validation-timeout: 3000
      pool-name: dts-transfer-api
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 600000
      leak-detection-threshold: 0
      initialization-fail-timeout: 1
    clickhouse:
      read:
        driver: ru.yandex.clickhouse.ClickHouseDriver
        url: jdbc:clickhouse://olap-yuuni.xxxx.co:80/poseidon
        user: yuuni_xxxx
        pwd: 3xxxxxxx
        max-active: 30
        min-idle: 5
        max-idle: 10
        max-wait: -1
      write:
        driver: ru.yandex.clickhouse.ClickHouseDriver
        url: jdbc:clickhouse://olap-yuuni-write.xxxxx.co:80/poseidon
        user: yuuni_xxxxx
        pwd: xxxxxxx
        max-active: 30
        min-idle: 5
        max-idle: 10
        max-wait: -1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#redis:
#  redisson:
#    nodes:
#      - "redis://172.23.47.15:7479"
#      - "redis://172.23.47.13:7481"
#      - "redis://172.23.47.14:7480"
#      - "redis://172.23.47.15:7480"
#      - "redis://172.23.47.13:7482"
#      - "redis://172.23.47.14:7481"

redis:
  nodes: 10.150.13.37:6830,10.150.13.35:6830,10.150.13.36:6830,10.150.13.37:6831,10.150.13.36:6831,10.150.13.35:6831

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

voyager:
  client:
    account: p_test
    secretKey: xxxxxxxx


pagehelper:
  # 指定数据库
  helper-dialect: mysql

master:
  listen-port: ${server.port}
  # master fetch command num
  fetch-command-num: 10
  # master prepare execute thread number to limit handle commands in parallel
  pre-exec-threads: 10
  # master execute thread number to limit process instances in parallel
  exec-threads: 100
  # master heartbeat interval
  heartbeat-interval: 10s
  registry-disconnect-strategy:
    # The disconnect strategy: stop, waiting
    strategy: waiting
    # The max waiting time to reconnect to registry if you set the strategy to waiting
    max-waiting-time: 100s

registry:
  type: zookeeper
  zookeeper:
    namespace: uat-cluster-scheduler
    connect-string: 10.150.65.63:2181
    retry-policy:
      base-sleep-time: 60ms
      max-sleep: 300ms
      max-retries: 5
    session-timeout: 30s
    connection-timeout: 9s
    block-until-connected: 2000ms
    digest: ~

oa-flow:
  base-url: https://uat-eeapi.xxxxxx.co
  token-app-id: xxxxxxxx
  token-app-secret: xxxxxxxxxxxx
  get-user-info-base-url: https://alter.xxxxx.co
  approver-list: nizhiqiang,liuguohui,liuminggang,v_wangzhenghui,v_yuanyongquan,chenwuzhou,mayangyang01,zhangyang01,zhouzhida,yuhao04,liubiwei,zhangxunxiang,dingguotao,niezhuang,gaoruichao,chencheng04,xuchen,xudonghui
  block:
    base-url: http://uat-incident.xxxxxx.co
    x-secretid: xxxxxxxxxx
    x-signature: xxxxxxxxxxx
    platform_id: 108
    platform_behavior_id: all
    env: 3
    app_id: infra.alter.bmr-cluster-scheduler-2
    source_type: 3

saber:
  notify:
    robotsList: 55
online:
  notify:
    robot: xxxxxxxxxxxxx
    userList: 028596,015860

bmr:
  base-url: http://uat-cloud-bm.xxxxxxx.co
  spark-manager:
    url: http://uat-bmr.xxxxxxx.co

dolphin:
  base-url: http://pre-bmr.scheduler.xxxxxx.co/dolphinscheduler
  deploy:
    token: xxxxxxxxxxxxxxxxx
  dqc:
    token: xxxxxxxxxxxxxxx
  admin:
    token: xxxxxxxxxxxxxxx
  project:
    add-fast-decomission-v2:
      schedProjectId: 13587658807520
      schedPipelineId: 13587760132960
    add-fast-decomission-v3:
      schedProjectId: 13587658807520
      schedPipelineId: 13588150324768
    dn-stop:
      schedProjectId: 13587658807520
      schedPipelineId: 13588375187232
    refresh-nn:
      schedProjectId: 13587658807520
      schedPipelineId: 13588380381792
    remove-decomission-v2:
      schedProjectId: 13587658807520
      schedPipelineId: 13631640763488
    remove-decomission-v3:
      schedProjectId: 13587658807520
      schedPipelineId: 13588150324768
    update-decomission-v2:
      schedProjectId: 13587658807520
      schedPipelineId: 13588180824480
    update-decomission-v3:
      schedProjectId: 13587658807520
      schedPipelineId: 13588150324768
spark:
  deploy:
    dev_Leader: zhangyang01,zhangwei24
    sre_Leader: hukai,liuminggang,liuguohui
  sql:
    translate:
      host: http://pre-sqltranslate.xxxxxxxxx.co/
  experiment:
    plus:
      host: http://pre-dolphinplus.xxxxxxx.co/
  client:
    pack:
      operate:
        projectId: 4385052-38057053-935
      pipelineId:
        type:
          clean: 7439680353-683-70
          remove: 7439680353-683-69
          download: 7439680353-683-68

com-caster:
  url: http://com.caster.bilibili.co
  api-token: xxxxxxxxxxxxxxxx
  platform-id: omega-xxxxxxxxxx-cmdb
caster:
  base-url: http://caster.xxxxxxxx.co
presto:
  tide:
    projectId: 15930388431968
    yarn:
      node:
        expansion: 15930414748128
        shrink: 15930421939680

hbo:
  prefix: http://pre-luckbear-api.xxxxxxxx.co
  deploy:
    dev_Leader: zhangyang01,zhangwei24,liuminggang,liuguohui
    sre_Leader: hukai,liuminggang,liuguohui
